version: '3.7'
networks:
  default:
    name: app-network
services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    image: ghcr.io/ivannn88888888/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/ivannn88888888/node-js-app:latest
    container_name: app
    restart: always
    environment:
      - PORT=3000
    networks:
      - default
