name: Build & Push to registry

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and Push Image
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive

    - name: Log in to registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker-compose build --pull

    - name: Push image
      run: docker-compose push

    - name: Run application
      run: docker-compose up -d

    - uses: haishanh/actions-telegram-notification@v1
      if: ${{ always() }}
      with:
        notification-token: ${{ secrets.NOTIFICATION_TOKEN }}
        job-status: ${{ job.status }}
